### ISSUE TITLE
[Kaggle notebook] Unable to train voices anymore since a few hours

### ISSUE THREAD

**Issue by KiON-GiON** [HirCoir/Piper-tts#3]
Hi there.

I was finetuning a voice since yesterday, however, since a few hours, when starting a new session, the notebook doesn't work anymore.

I noticed something in the output: While numpy 1.21.5 was built and installed successfully, something makes it reinstall the newest version (2.0.0) and it causes compatibility issues and the notebook fails.

**Comment by floresernesto95** [comment]
Hi man, did u solve it? Im getting the same error here.

/kaggle/working/piper/src/python
Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/conda/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/kaggle/working/piper/src/python/piper_train/preprocess.py", line 28, in <module>
    from .norm_audio import cache_norm_audio, make_silence_detector
  File "/kaggle/working/piper/src/python/piper_train/norm_audio/__init__.py", line 8, in <module>
    from piper_train.vits.mel_processing import spectrogram_torch
  File "/kaggle/working/piper/src/python/piper_train/vits/mel_processing.py", line 3, in <module>
    from librosa.filters import mel as librosa_mel_fn
  File "/opt/conda/lib/python3.10/site-packages/librosa/filters.py", line 52, in <module>
    from numba import jit
  File "/opt/conda/lib/python3.10/site-packages/numba/__init__.py", line 59, in <module>
    _ensure_critical_deps()
  File "/opt/conda/lib/python3.10/site-packages/numba/__init__.py", line 45, in _ensure_critical_deps
    raise ImportError(msg)
ImportError: Numba needs NumPy 2.0 or less. Got NumPy 2.1.

**Comment by KiON-GiON** [comment]
I solved it by changing the following line:

``
!python3 -m pip install --no-binary numpy numpy==1.21.5
``
To
``
!pip install --force-reinstall numpy==1.26.4
``

**Comment by floresernesto95** [comment]
Nice, thanks for the help bro!
